### ISSUE TITLE
Request to upload the pre-trained glove embeddings on various corpora for reproducibility purposes

### ISSUE THREAD

**Issue by theartpiece** [nlpsoc/reliability_bias#1]

**Comment by Yupei-Du** [comment]
Hi, 

Thank you for the request. Unfortunately, the files are so large that it is hard to upload them here. However, we believe you can almost reproduce the results by downloading the training data and running pre-processing following instructions in ```data/train_corpora/```. If you still cannot, we will explore options to upload these embeddings.
